before_script:
  # Switch user to ubuntu and run a command
  - echo "Switching to ubuntu user"
  - sudo -u ubuntu whoami
stages:
  - verify
  - build
  - deploy
variables: 
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
verify:
  stage: verify
  script: 
    - echo "user"
    - whoami
build:
  stage: build  
  script:
    - echo "System Username:"

    - echo  $IMAGE_TAG 
    - docker build -t ${IMAGE_NAME} .
    - echo "Pushing Docker image to GitLab container registry..."
    - docker push ${IMAGE_NAME}


# deploy:
#     stage: deploy
#     script:
#       - docker run -d --name= $IMAGE_TAG  writeonce-frontend-container -v /tmp:/app/dist/browser
#       - docker cp /tmp writeonce-webserver:/usr/share/nginx/html/