before_script:
  # Install Docker in the Alpine container
  - apk update && apk add --no-cache docker openrc
  # Enable and start Docker service
  - rc-update add docker boot
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - apk add --no-cache openssh-client


stages:
  - verify
  - build
  - deploy
variables: 
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
verify:
  stage: verify
  script: 
    - echo "user"
    - whoami
    - cat /etc/os-release
build:
  stage: build  
  script:
    - echo "System Username:"

    - echo  $IMAGE_TAG 
    - docker build -t ${IMAGE_NAME} .


deploy:
    stage: deploy
    script:
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - docker run --rm registry.writeonce.de/shoney/writeonce-app sh -c "tar -czf - -C browser . "
       | ssh -o StrictHostKeyChecking=no deployer@writeonce.de 'docker exec -i writeonce-webserver tar -xzf - -C /usr/share/nginx/html/'
      - docker cp /tmp writeonce-webserver:/usr/share/nginx/html/
      - ssh-agent -k