FROM node:latest as build
RUN npm install -g @angular/cli
RUN mkdir -p /usr/scr/app
WORKDIR /usr/scr/app

COPY ./package.json /usr/scr/app

# Install all the dependencies
RUN npm install;
COPY ./ /usr/scr/app
EXPOSE 4200
CMD ["npm","start"]
