services:
  writeonce-frontend:
    build: 
      context: .
      dockerfile: Dockerfile-Dev
    image: writeonce-frontend:dev
    container_name: writeonce-frontend-container
    ports:
      - 4200:4200
    
    volumes:
      - .:/app
      - /app/node_modules