FROM node:18 as build
RUN npm install -g @angular/cli
RUN mkdir -p /app
WORKDIR /app

COPY package*.json /app

# Install all the dependencies
RUN npm install;
COPY ./ /app
EXPOSE 4200
CMD ["npm","start"]
